In [1]:
import numpy as np

In [2]:
np.arange(10).resharp(3,3)

AttributeError: 'numpy.ndarray' object has no attribute 'resharp'

In [3]:
t1=np.arange(10)

In [4]:
t2=t1.reshape(3,3)

ValueError: cannot reshape array of size 10 into shape (3,3)

In [5]:
t2=t1.reshape(2,5)
print(t2)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [6]:
from PIL import Image

In [7]:
img = Image.open("./img/time.jpg")

FileNotFoundError: [Errno 2] No such file or directory: './img/time.jpg'

In [10]:
img = Image.open(".\img\time.jpg")

OSError: [Errno 22] Invalid argument: '.\\img\time.jpg'

In [11]:
img = Image.open("..\img\time.jpg")

OSError: [Errno 22] Invalid argument: '..\\img\time.jpg'

In [12]:
img = Image.open('./img/timg.jpg')

In [13]:
print(type(img))

<class 'PIL.JpegImagePlugin.JpegImageFile'>


In [15]:
img2=np.array(img)

In [16]:
print("img2",img2.shape)

img2 (300, 300, 3)


In [17]:
img2=[255,255,255]-img2

In [18]:
print("img2",img2.shape)

img2 (300, 300, 3)


In [19]:
print(img2)

[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]


In [22]:
img3=Image.fromarray(img2)

TypeError: Cannot handle this data type: (1, 1, 3), <i4

In [23]:
img = Image.open('./img/timg.jpg')

In [24]:
img2=np.array(img)

In [25]:
print(img2)

[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]


In [26]:
img3=[255,255,255]-img2

In [32]:
img4=np.asarray(img3,dtype=np.uint8)

In [28]:
print(img3)

[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]


In [33]:
print(img4)

[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]


In [34]:
img5=Image.fromarray(img4)

# qweqw

In [35]:
img5.save('./img/timg2.jpg')