In [1]:
from PIL import Image
import numpy as np

In [5]:
data=Image.open("./numpy_demo.data/phone.jpg")#加载图片

In [6]:
print(data,type(data))

<PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=400x400 at 0x722FAC8> <class 'PIL.JpegImagePlugin.JpegImageFile'>


In [7]:
im=np.array(data)#将读入图片转换为ndarray

In [8]:
print(im)

[[[ 8  8  8]
  [ 8  8  8]
  [ 8  8  8]
  ...
  [ 6  6  6]
  [ 6  6  6]
  [ 6  6  6]]

 [[ 9  9  9]
  [ 9  9  9]
  [ 9  9  9]
  ...
  [ 6  6  6]
  [ 6  6  6]
  [ 6  6  6]]

 [[11 11 11]
  [11 11 11]
  [11 11 11]
  ...
  [ 6  6  6]
  [ 6  6  6]
  [ 6  6  6]]

 ...

 [[ 5  5  5]
  [13 13 13]
  [25 25 25]
  ...
  [ 6  6  6]
  [ 3  3  3]
  [ 2  2  2]]

 [[25 25 25]
  [26 26 26]
  [22 22 22]
  ...
  [ 0  0  0]
  [ 0  0  0]
  [ 1  1  1]]

 [[21 21 21]
  [10 10 10]
  [ 0  0  0]
  ...
  [ 3  3  3]
  [ 4  4  4]
  [ 4  4  4]]]


In [15]:
print(im.shape,im.dtype)#显示大小和元素类型

(400, 400, 3) uint8


In [17]:
b=[255,255,255]-im #运算求补色

In [20]:
new_im=Image.fromarray(b.astype(np.uint8))#将ndarray又转化为图片格式

In [21]:
new_im.save("./numpy_demo.data/phone2.jpg")#另存为补色图片

In [23]:
new_im.show()#展示